// Mocks generated by Mockito 5.4.6 from annotations
// in cleanarch/test/profile/profiledatasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cleanarch/features/profile/data/datasources/profiledatasource.dart'
    as _i3;
import 'package:cleanarch/features/profile/data/models/profile.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfilemodel_0 extends _i1.SmartFake implements _i2.Profilemodel {
  _FakeProfilemodel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Profiledatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfiledatasource extends _i1.Mock implements _i3.Profiledatasource {
  @override
  _i4.Future<_i2.Profilemodel> getUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue: _i4.Future<_i2.Profilemodel>.value(
              _FakeProfilemodel_0(this, Invocation.method(#getUser, [id])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Profilemodel>.value(
              _FakeProfilemodel_0(this, Invocation.method(#getUser, [id])),
            ),
          )
          as _i4.Future<_i2.Profilemodel>);

  @override
  _i4.Future<List<_i2.Profilemodel>> getalluser(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#getalluser, [page]),
            returnValue: _i4.Future<List<_i2.Profilemodel>>.value(
              <_i2.Profilemodel>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.Profilemodel>>.value(
              <_i2.Profilemodel>[],
            ),
          )
          as _i4.Future<List<_i2.Profilemodel>>);
}
